### ISSUE TITLE
Add option to show scrollbar always

### ISSUE THREAD

**Issue by Smile4ever** [bwinton/TabCenter#1070]
It would be nice if I could set the scrollbar to "always display".

**Comment by Keith94** [comment]
If you don't mind a CSS workaround, you can try:

```css
 #main-window[tabspinned="true"] #verticaltabs-box #tabbrowser-tabs .tabbrowser-arrowscrollbox > scrollbox {
    overflow-y: auto !important;
}
```
