### ISSUE TITLE
border-left in maximized mode

### ISSUE THREAD

**Issue by fx4waldi** [bwinton/TabCenter#150]
If the window is maximized on the left side there is a border (light.css:405). This prevents navigation when the cursor is at the edge of the screen.

**Comment by bwinton** [comment]
Could add a `border-left: 0 !important` to https://github.com/bwinton/VerticalTabs/blob/master/skin/light/light.css#L67

**Comment by Keith94** [comment]
Just remove code from `win.css`:

```css
#verticaltabs-box {
    border-left: 1px solid rgb(160, 160, 160);
  }
```
