### ISSUE TITLE
Add option to disable animations

### ISSUE THREAD

**Issue by heuripedes** [bwinton/TabCenter#740]
I would like to request the addition of an option to disable animations, I don't mind if it's only available in about:config. The fadeout animation slows down middle-click tab closing and waiting for TabCenter to slide when you have it in "shrink" mode is really annoying.

**Comment by benoit-pierre** [comment]
As a workaround, for disabling up animations, I just added this in my "Custom css code" tab in Classic Theme Restorer:
```css
.tabbrowser-tab.tab-hidden {
  animation: 0ms tab-fade-out !important;
}
.tabbrowser-tab.tab-visible {
  animation: 0ms tab-fade-in !important;
}
.large-tabs .tabbrowser-tab.tab-hidden {
  animation: 0ms large-tab-fade-out !important;
}
.large-tabs .tabbrowser-tab.tab-visible {
  animation: 0ms large-tab-fade-in !important;
}
.tabbrowser-tab.tab-hidden .tab-stack {
  transition: visibility 0ms 0ms !important;
}
```
