### ISSUE TITLE
Option for hiding close button

### ISSUE THREAD

**Issue by gadelat** [bwinton/TabCenter#761]
I want to prevent acidentally clicking on close button by not showing it. I always close tabs by mouse middle click.

**Comment by bwinton** [comment]
While this is a totally valid use-case, I don't believe it's general enough to warrant adding an option…  So, I think I'm going to close this as 'wontfix', but thank you for the suggestion!

**Comment by ChrisW-B** [comment]
@gadelat If you have stylish you can just create a style with the code 
```css
@namespace url("http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul");

.tab-close-button.close-icon{
  display:none!important;
}
```
and it will hide your tab close buttons

**Comment by bwinton** [comment]
Thank you, @ChrisW-B!  I was going to recommend Stylish, but it didn't look like it could modify Firefox's UI, so I didn't…

**Comment by gadelat** [comment]
@ChrisW-B doesn't work

Too bad, I'll have to use tree style tabs instead of this then.

**Comment by ChrisW-B** [comment]
@gadelat huh, you're right! Stylish is weird sometimes, but I tried again on a clean profile and

```css
.tab-close-button.close-icon {
  visibility:collapse!important
}
```
seems to work for me, but I'm out of ideas after that :/
