### ISSUE TITLE
Feature Request: Add some kind of highlighting option or other ui indicator for tabs that aren't loaded.

### ISSUE THREAD

**Issue by Shickmo** [bwinton/TabCenter#822]
So my thought was when tabs are loaded or your opening the browser and have a bunch of tabs load from the last session it would be nice to have some kind of ui queue, color or configurable option, to signify a tab or tabs are not currently loaded. That way I will know upon click it will take a moment to load.

Thanks for your consideration.

**Comment by ChrisW-B** [comment]
If you have stylish, this script will fade unloaded tabs, and it works great with tabcenter!
```css
@namespace url(http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul);

.tabbrowser-tab[pending], .alltabs-item[pending] { transition:opacity .2s ease-in-out; opacity: 0.4 !important; }
.tabbrowser-tab[pending]:hover, .alltabs-item[pending]:hover { opacity:1 !important; }

```
